import { useState } from 'react'
import { BrowserRouter, Link, Navigate, Route, Routes, useLocation, useNavigate } from 'react-router-dom'
import { toast, Toaster } from 'react-hot-toast'
import { Bell, Check, ChevronRight, Clapperboard, Clock3, Download, Film, Headphones, Image, LayoutDashboard, LockKeyhole, LogOut, MoreHorizontal, Music2, Pause, Play, Plus, Redo2, Save, Search, Settings, Sparkles, Trash2, WandSparkles, Volume2 } from 'lucide-react'
import './App.css'

const initialProject = { id: 'aurora-01', title: 'Aurora Protocol', idea: 'A memory architect discovers the last unedited human dream.', genre: 'Sci-Fi', tone: 'Atmospheric', platform: 'Short film' }
const images = ['https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=1000&q=85', 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1000&q=85', 'https://images.unsplash.com/photo-1534791547706-7b57579e65d0?auto=format&fit=crop&w=1000&q=85']

function App() {
  const [user, setUser] = useState(null)
  const [project, setProject] = useState(initialProject)
  const [approvals, setApprovals] = useState({ script: false, scenes: false, media: false, video: false })
  const [isGenerating, setIsGenerating] = useState(false)
  const approve = (key) => { setApprovals((value) => ({ ...value, [key]: true })); toast.success(`${key[0].toUpperCase() + key.slice(1)} approved`) }

  return (
    <BrowserRouter><Toaster position="bottom-right" toastOptions={{ style: { background: '#151925', color: '#f5f7ff', border: '1px solid #2b3448' } }} />
      <Routes>
        <Route path="/" element={user ? <Navigate to="/dashboard" replace /> : <Login onLogin={() => setUser({ name: 'Maya Chen' })} />} />
        <Route path="/register" element={<Login register onLogin={() => setUser({ name: 'Maya Chen' })} />} />
        <Route path="*" element={user ? <AppShell user={user} project={project} approvals={approvals}><RoutesContent project={project} setProject={setProject} approvals={approvals} approve={approve} isGenerating={isGenerating} setIsGenerating={setIsGenerating} /></AppShell> : <Navigate to="/" replace />} />
      </Routes>
    </BrowserRouter>
  )
}

function Login({ register, onLogin }) { const navigate = useNavigate(); return <main className="auth-page"><div className="auth-visual"><div className="brand-mark"><Clapperboard size={18} /> CINE<span>CRAFT</span></div><div className="auth-quote"><p>YOUR STORY.<br /><em>AMPLIFIED.</em></p><small>AI filmmaking for the stories that stay with you.</small></div><div className="auth-orbit">✦</div></div><section className="auth-form"><div className="mobile-brand brand-mark"><Clapperboard size={18} /> CINE<span>CRAFT</span></div><span className="eyebrow">{register ? 'Join the studio' : 'Welcome back'}</span><h1>{register ? 'Create your account' : 'Bring your vision to life.'}</h1><p className="muted">{register ? 'Start crafting your next unforgettable story.' : 'Sign in to continue your cinematic journey.'}</p>{register && <label>Full name<input placeholder="Maya Chen" /></label>}<label>Email address<input type="email" placeholder="you@studio.com" /></label><label>Password<input type="password" placeholder="••••••••" /></label><button className="button primary wide" onClick={() => { onLogin(); navigate('/dashboard') }}>{register ? 'Create account' : 'Enter the studio'} <ChevronRight size={16} /></button><div className="auth-divider"><span /> or <span /></div><button className="button social"><span>G</span> Continue with Google</button><p className="auth-switch">{register ? 'Already have an account?' : 'New to CineCraft?'} <Link to={register ? '/' : '/register'}>{register ? 'Sign in' : 'Create account'}</Link></p></section></main> }

function AppShell({ user, project, children }) { const navigate = useNavigate(); const location = useLocation(); return <div className="app-shell"><aside className="sidebar"><Link to="/dashboard" className="brand-mark"><Clapperboard size={18} /> CINE<span>CRAFT</span></Link><nav><small>WORKSPACE</small><Link className={location.pathname.includes('dashboard') ? 'active' : ''} to="/dashboard"><LayoutDashboard size={17} /> Overview</Link><Link className={location.pathname.includes('history') ? 'active' : ''} to="/history"><Clock3 size={17} /> Project history</Link><small>CREATE</small><Link className={location.pathname.includes('create') ? 'active' : ''} to="/create"><Plus size={17} /> New project</Link></nav><div className="sidebar-bottom"><Link to="/profile"><Settings size={17} /> Preferences</Link><button onClick={() => navigate('/')}><LogOut size={17} /> Sign out</button><div className="mini-user"><div className="avatar">MC</div><div><strong>{user.name}</strong><small>Creator plan</small></div><MoreHorizontal size={16} /></div></div></aside><main className="main-area"><header className="topbar"><div className="crumb">Studio <ChevronRight size={14} /> <strong>{project.title}</strong></div><div className="top-actions"><button className="icon-button"><Search size={18} /></button><button className="icon-button notification"><Bell size={18} /><i /></button><div className="avatar">MC</div></div></header>{children}</main></div> }

const steps = [{ key: 'idea', label: 'Idea', path: 'create' }, { key: 'script', label: 'Script', path: 'script' }, { key: 'scenes', label: 'Scenes', path: 'scenes' }, { key: 'media', label: 'Media', path: 'media' }, { key: 'video', label: 'Video', path: 'video' }, { key: 'export', label: 'Export', path: 'export' }]
function Workflow({ approvals, current }) { const navigate = useNavigate(); const unlocked = { idea: true, script: true, scenes: approvals.script, media: approvals.scenes, video: approvals.media, export: approvals.video }; return <div className="workflow">{steps.map((step, index) => <button key={step.key} className={`${current === step.key ? 'current' : ''} ${unlocked[step.key] ? '' : 'locked'}`} onClick={() => unlocked[step.key] && navigate(step.path === 'create' ? '/create' : `/project/${'aurora-01'}/${step.path}`)}><span className="step-dot">{approvals[step.key] ? <Check size={13} /> : !unlocked[step.key] ? <LockKeyhole size={11} /> : index + 1}</span><span>{step.label}</span>{index < steps.length - 1 && <i />}</button>)}</div> }

function GatedRoute({ allowed, children }) { return allowed ? children : <Navigate to="/project/aurora-01/script" replace /> }
function RoutesContent({ project, setProject, approvals, approve, isGenerating, setIsGenerating }) { return <Routes><Route path="/dashboard" element={<Dashboard project={project} />} /><Route path="/create" element={<CreateProject setProject={setProject} />} /><Route path="/history" element={<History project={project} />} /><Route path="/profile" element={<Profile />} /><Route path="/project/:id/script" element={<Script project={project} approve={approve} approvals={approvals} isGenerating={isGenerating} setIsGenerating={setIsGenerating} />} /><Route path="/project/:id/scenes" element={<GatedRoute allowed={approvals.script}><Scenes approve={approve} approvals={approvals} isGenerating={isGenerating} setIsGenerating={setIsGenerating} /></GatedRoute>} /><Route path="/project/:id/media" element={<GatedRoute allowed={approvals.scenes}><Media approve={approve} approvals={approvals} /></GatedRoute>} /><Route path="/project/:id/video" element={<GatedRoute allowed={approvals.media}><Video approve={approve} /></GatedRoute>} /><Route path="/project/:id/export" element={<GatedRoute allowed={approvals.video}><Export project={project} /></GatedRoute>} /><Route path="*" element={<Navigate to="/dashboard" replace />} /></Routes> }

function Page({ current, approvals, title, intro, children, action }) { return <div className="page"><Workflow current={current} approvals={approvals} /><div className="page-heading"><div><span className="eyebrow">{current === 'idea' ? 'New project' : `Chapter 0${steps.findIndex((step) => step.key === current)}`}</span><h1>{title}</h1><p className="muted">{intro}</p></div>{action}</div>{children}</div> }
const Button = ({ children, className = '', onClick, disabled }) => <button disabled={disabled} onClick={onClick} className={`button ${className}`}>{children}</button>
function Dashboard({ project }) { const navigate = useNavigate(); return <Page current="idea" approvals={{}} title={<>Good evening, Maya <span className="wave">✦</span></>} intro="Ready to turn a spark into something unforgettable?" action={<Button className="primary" onClick={() => navigate('/create')}><Plus size={17} /> New project</Button>}><section className="stats-grid"><div className="stat-card"><small>Projects created</small><strong>12</strong><span className="trend">↗ 18% this month</span></div><div className="stat-card"><small>In production</small><strong>03</strong><span className="muted">Across 2 projects</span></div><div className="stat-card"><small>Studio hours</small><strong>48.5</strong><span className="muted">This month</span></div></section><div className="section-head"><div><h2>Continue creating</h2><p className="muted">Pick up where you left off.</p></div><Link to="/history" className="text-link">View all <ChevronRight size={15} /></Link></div><ProjectCard project={project} /><div className="section-head"><div><h2>Recent projects</h2><p className="muted">Your latest cinematic worlds.</p></div></div><div className="project-grid"><ProjectTile title="The Quiet Between" genre="Drama · 04:12" image={images[1]} /><ProjectTile title="Neon Afterglow" genre="Music video · 02:48" image={images[2]} /></div></Page> }
function ProjectCard({ project }) { const navigate = useNavigate(); return <div className="featured-project"><img src={images[0]} alt="Aurora Protocol mood" /><div className="featured-copy"><div className="status-pill"><span /> In production</div><h2>{project.title}</h2><p>{project.idea}</p><div className="progress-label"><span>Production progress</span><strong>42%</strong></div><div className="progress"><i style={{ width: '42%' }} /></div><div className="featured-meta"><span>Last edited 2 hours ago</span><Button className="secondary" onClick={() => navigate('/project/aurora-01/script')}>Continue <ChevronRight size={15} /></Button></div></div></div> }
function ProjectTile({ title, genre, image }) { return <div className="project-tile"><img src={image} alt="" /><div><h3>{title}</h3><p>{genre}</p></div><MoreHorizontal size={18} /></div> }
function CreateProject({ setProject }) { const navigate = useNavigate(); const [title, setTitle] = useState(''); return <Page current="idea" approvals={{}} title="Start with a spark." intro="Give your story a pulse. You can shape every detail later."><div className="form-layout"><div className="glass-card project-form"><div className="card-title"><div className="title-icon cyan"><Sparkles size={18} /></div><div><h2>Project brief</h2><p className="muted">The seed of your next film.</p></div></div><label>Project title<input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="e.g. Aurora Protocol" /></label><label>One-line idea<textarea placeholder="A memory architect discovers the last unedited human dream." /></label><div className="form-row"><label>Content type<select><option>Short film</option><option>Music video</option><option>Commercial</option></select></label><label>Genre<select><option>Sci-Fi</option><option>Drama</option><option>Documentary</option></select></label></div><div className="form-row"><label>Tone<select><option>Atmospheric</option><option>Energetic</option><option>Intimate</option></select></label><label>Target platform<select><option>Festival / Cinema</option><option>YouTube</option><option>Social</option></select></label></div><Button className="primary wide" onClick={() => { setProject((value) => ({ ...value, title: title || 'Aurora Protocol' })); toast.success('Project created'); navigate('/project/aurora-01/script') }}><WandSparkles size={17} /> Generate my script <ChevronRight size={16} /></Button></div><div className="idea-aside"><div className="aside-orbit"><Film size={24} /></div><h3>Every great film starts with a feeling.</h3><p>Describe the world in your head. CineCraft will help you find the story inside it.</p></div></div></Page> }
function Script({ project, approve, approvals, isGenerating, setIsGenerating }) { const navigate = useNavigate(); const generate = () => { setIsGenerating(true); setTimeout(() => { setIsGenerating(false); toast.success('Script regenerated'); }, 900) }; return <Page current="script" approvals={approvals} title="The story takes shape." intro="Review the AI-generated treatment, then make it yours." action={<div className="heading-actions"><Button className="secondary" onClick={generate}><Redo2 size={16} /> Regenerate</Button><Button className="primary" onClick={() => { approve('script'); navigate('/project/aurora-01/scenes') }}><Check size={16} /> Approve script</Button></div>}><div className="editor-layout"><div className="glass-card script-editor">{isGenerating && <div className="generating"><Sparkles size={16} /> Weaving your story...</div>}<div className="editor-top"><span className="status-pill"><span className="purple-dot" /> AI draft</span><span className="muted">Edited just now</span></div><label>Working title<input defaultValue={project.title} /></label><label>Logline<textarea defaultValue={project.idea} /></label><div className="script-section"><h3>Story treatment</h3><p>In a city where dreams are archived before they fade, Elian Voss restores memories for a living. When a corrupted file contains a dream that feels impossibly real, she follows its fragments through the sleeping minds of strangers.</p></div><div className="script-section"><h3>Characters <span className="count">03</span></h3><div className="character-row"><div className="avatar purple">EV</div><div><strong>Elian Voss</strong><p className="muted">Memory architect · Protagonist</p></div></div><div className="character-row"><div className="avatar pink">AN</div><div><strong>Arden Null</strong><p className="muted">The voice inside the dream</p></div></div></div><div className="editor-footer"><span className="muted">Autosaved 11:42 PM</span><Button className="secondary"><Save size={15} /> Save changes</Button></div></div><div className="insight-card"><div className="insight-head"><Sparkles size={17} /><span>Story insight</span></div><h3>Strong emotional core</h3><p>The contrast between archived memories and a living dream creates a compelling visual metaphor for human connection.</p><div className="tag-row"><span>#identity</span><span>#memory</span><span>#wonder</span></div></div></div></Page> }
function Scenes({ approve, approvals, isGenerating, setIsGenerating }) { const [selected, setSelected] = useState(1); const navigate = useNavigate(); return <Page current="scenes" approvals={approvals} title="Direct every moment." intro="Three scenes drafted from your approved script." action={<div className="heading-actions"><Button className="secondary" onClick={() => { setIsGenerating(true); setTimeout(() => setIsGenerating(false), 800) }}><Redo2 size={16} /> Regenerate all</Button><Button className="primary" onClick={() => { approve('scenes'); navigate('/project/aurora-01/media') }}><Check size={16} /> Approve scenes</Button></div>}><div className="scene-layout"><div className="scene-list">{[1, 2, 3].map((number) => <button key={number} className={`scene-list-item ${selected === number ? 'selected' : ''}`} onClick={() => setSelected(number)}><img src={images[number - 1]} alt="" /><div><small>SCENE 0{number} · {number === 1 ? '00:32' : number === 2 ? '00:48' : '01:06'}</small><strong>{['The Archive', 'A crack in the dark', 'The last dream'][number - 1]}</strong></div><ChevronRight size={15} /></button>)}<button className="add-scene"><Plus size={15} /> Add scene</button></div><div className="glass-card scene-editor"><div className="scene-preview"><img src={images[selected - 1]} alt="Scene preview" /><span>SCENE 0{selected}</span><Button className="icon-button"><Play size={17} /></Button></div>{isGenerating && <div className="generating"><Sparkles size={16} /> Reimagining scenes...</div>}<div className="scene-fields"><div className="field-header"><div><span className="eyebrow">Scene 0{selected}</span><h2>{['The Archive', 'A crack in the dark', 'The last dream'][selected - 1]}</h2></div><Button className="ghost"><MoreHorizontal size={18} /></Button></div><label>Description<textarea defaultValue={selected === 1 ? 'INT. MEMORY ARCHIVE - NIGHT\nRows of glass capsules glow in the blue dark. Elian moves between them, listening.' : 'A pulse of warm light breaks through the archive.'} /></label><div className="form-row"><label>Character<input defaultValue="Elian Voss" /></label><label>Location<input defaultValue="Memory Archive" /></label></div><label>Image prompt<input defaultValue="cinematic wide shot, ethereal archive, blue volumetric light, 35mm film grain" /></label><label>Audio prompt<input defaultValue="low room tone, distant analog hum, soft footsteps" /></label><div className="editor-footer"><span className="muted">Duration · <strong>00:{selected === 1 ? '32' : selected === 2 ? '48' : '06'}</strong></span><Button className="secondary"><Save size={15} /> Save scene</Button></div></div></div></div></Page> }
function Media({ approve, approvals }) { const navigate = useNavigate(); const [imageIndex, setImageIndex] = useState(0); return <Page current="media" approvals={approvals} title="Give it a world." intro="Shape the visual and sonic identity of each scene." action={<Button className="primary" onClick={() => { approve('media'); navigate('/project/aurora-01/video') }}><Check size={16} /> Approve media</Button>}><div className="media-layout"><div className="glass-card media-preview"><div className="media-image"><img src={images[imageIndex]} alt="Generated scene" /><span className="image-badge"><Image size={14} /> Scene 01</span></div><div className="media-controls"><div><h2>The Archive</h2><p className="muted">Visual generation · v3</p></div><Button className="secondary" onClick={() => { setImageIndex((imageIndex + 1) % images.length); toast.success('Only this image was regenerated') }}><Redo2 size={15} /> Regenerate image</Button></div></div><div className="media-stack"><AudioTrack color="pink" icon={<Volume2 size={17} />} title="Narration" meta="Elian Voss · 00:32" /><AudioTrack color="magenta" icon={<Music2 size={17} />} title="Original score" meta="Nocturne in C · 01:18" /><AudioTrack color="green" icon={<Headphones size={17} />} title="Sound design" meta="Archive room tone · 00:45" /><Button className="secondary wide"><Plus size={15} /> Add audio layer</Button></div></div></Page> }
function AudioTrack({ color, icon, title, meta }) { const [playing, setPlaying] = useState(false); return <div className="audio-track"><div className={`audio-icon ${color}`}>{icon}</div><div className="audio-copy"><strong>{title}</strong><p className="muted">{meta}</p><div className="waveform">{Array.from({ length: 28 }, (_, index) => <i key={index} style={{ height: `${10 + ((index * 17) % 22)}px` }} />)}</div></div><button className="play-small" onClick={() => setPlaying(!playing)}>{playing ? <Pause size={15} /> : <Play size={15} />}</button></div> }
function Video({ approve }) { const [playing, setPlaying] = useState(false); const navigate = useNavigate(); return <Page current="video" approvals={{ script: true, scenes: true, media: true, video: false }} title="See it move." intro="Your film, assembled into one living timeline." action={<Button className="primary" onClick={() => { approve('video'); navigate('/project/aurora-01/export') }}><Film size={16} /> Generate final video</Button>}><div className="video-layout"><div className="video-frame"><img src={images[0]} alt="Video preview" /><div className="video-overlay"><span>PREVIEW · 1080P</span><button onClick={() => setPlaying(!playing)}>{playing ? <Pause size={24} /> : <Play size={24} />}</button><div className="video-time">00:18 <span>/ 02:26</span></div></div></div><div className="timeline-card glass-card"><div className="timeline-head"><div><h3>Timeline</h3><p className="muted">Aurora Protocol · 3 scenes</p></div><span className="status-pill"><span /> Ready to generate</span></div><div className="ruler">{['00:00', '00:30', '01:00', '01:30', '02:00'].map((time) => <span key={time}>{time}</span>)}</div>{[['Visuals', 'cyan'], ['Narration', 'pink'], ['Music', 'purple']].map(([name, color]) => <div className="track" key={name}><span>{name}</span><div className={`track-bar ${color}`}><i /><i /><i /></div></div>)}<div className="playhead" /></div></div></Page> }
function Export({ project }) { return <Page current="export" approvals={{ script: true, scenes: true, media: true, video: true }} title="It’s ready for the world." intro="Your final cut is waiting." action={<Button className="primary"><Download size={16} /> Download video</Button>}><div className="export-layout"><div className="export-frame"><img src={images[0]} alt="Final video cover" /><div className="export-play"><Play size={22} /></div><div className="export-label"><Check size={14} /> FINAL CUT · 1080P</div></div><div className="glass-card export-info"><div className="status-pill green-status"><span /> Completed</div><h2>{project.title}</h2><p className="muted">Created August 24, 2026 · 02:26</p><div className="export-details"><span>Resolution <strong>1920 × 1080</strong></span><span>Format <strong>MP4 · H.264</strong></span><span>File size <strong>184 MB</strong></span></div><Button className="secondary wide"><Download size={16} /> Download final cut</Button><Button className="ghost wide"><Redo2 size={15} /> Create a new version</Button></div></div></Page> }
function History({ project }) { return <Page current="idea" approvals={{}} title="Project history" intro="Every story you have started, in one place." action={<Button className="primary"><Plus size={16} /> New project</Button>}><div className="history-toolbar"><div className="search-field"><Search size={16} /><input placeholder="Search projects" /></div><select><option>All projects</option><option>In production</option><option>Completed</option></select></div><div className="history-list"><ProjectRow project={project} image={images[0]} progress="42%" status="In production" /><ProjectRow project={{ title: 'The Quiet Between', idea: 'Two strangers share a moment in a city that never sleeps.' }} image={images[1]} progress="100%" status="Completed" /><ProjectRow project={{ title: 'Neon Afterglow', idea: 'A visual poem for the final night of summer.' }} image={images[2]} progress="76%" status="In production" /></div></Page> }
function ProjectRow({ project, image, progress, status }) { return <div className="project-row"><img src={image} alt="" /><div className="row-main"><h3>{project.title}</h3><p className="muted">{project.idea}</p></div><div className="row-status"><span className={`status-dot ${status === 'Completed' ? 'done' : ''}`} />{status}</div><div className="row-progress"><span>{progress}</span><div className="progress"><i style={{ width: progress }} /></div></div><MoreHorizontal size={18} /></div> }
function Profile() { return <Page current="idea" approvals={{}} title="Your studio profile" intro="Personalize your CineCraft experience."><div className="profile-card glass-card"><div className="profile-cover" /><div className="profile-content"><div className="avatar profile-avatar">MC</div><h2>Maya Chen</h2><p className="muted">maya.chen@studio.com</p><div className="profile-form"><label>Display name<input defaultValue="Maya Chen" /></label><label>Creative focus<select><option>Film & storytelling</option><option>Music videos</option></select></label><Button className="primary"><Save size={15} /> Save profile</Button></div></div></div><button className="danger-link"><Trash2 size={15} /> Delete account</button></Page> }

export default App
